Mode: dev

Name: product-api
Host: 0.0.0.0
Port: 9802

JwtAuth:
  AccessSecret: 840f98f283c7e914f98a87c3f30b3f2f
  AccessExpire: 7200

ProductRpcConf:
  Etcd:
    Hosts:
      - goms_etcd:2379
    Key: product-rpc
  NonBlock: true