version: '3'

#API网关、热重载环境
#docker compose -f docker-compose.yml up -d
#所有绑定目录放在/bind/conf/*、/bind/data/*、/bind/logs/*内

services:
  #Nginx网关【mkdir -p /bind/conf/nginx /bind/logs/nginx】
  nginx:
    image: nginx:1.23.3
    container_name: goms_nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /bind/conf/nginx:/etc/nginx/conf.d
      - /bind/logs/nginx:/var/log/nginx
    privileged: true
    restart: always
    networks:
      - goms_net

  #App热加载容器【mkdir -p /bind/data/air】
  app-user-api:
    image: cosmtrek/air:latest
    container_name: goms_app_user_api
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 9801:9801
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c app/user/api/air.toml
    networks:
      - goms_net

  app-user-rpc:
    image: cosmtrek/air:latest
    container_name: goms_app_user_rpc
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 9901:9901
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c app/user/rpc/air.toml
    networks:
      - goms_net

networks:
  goms_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

