version: '3'

#API网关、热重载环境
#docker compose -f docker-compose.yml up -d
#所有绑定目录放在/bind/conf/*、/bind/data/*、/bind/logs/*内

services:
  #Nginx网关
  nginx:
    image: nginx:1.23.3
    container_name: goms_nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /bind/conf/nginx:/etc/nginx/conf.d
      - /bind/logs/nginx:/var/log/nginx
    privileged: true
    restart: always
    networks:
      - goms_net

  #App热加载容器
  auth-api:
    image: cosmtrek/air:latest
    container_name: goms_service_auth_api
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7800:7800
      - 9800:9800
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/auth/api/air.toml
    networks:
      - goms_net

  user-api:
    image: cosmtrek/air:latest
    container_name: goms_service_user_api
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7801:7801
      - 9801:9801
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/user/api/air.toml
    networks:
      - goms_net

  user-rpc:
    image: cosmtrek/air:latest
    container_name: goms_service_user_rpc
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7901:7901
      - 9901:9901
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/user/rpc/air.toml
    networks:
      - goms_net


  product-api:
    image: cosmtrek/air:latest
    container_name: goms_service_product_api
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7802:7802
      - 9802:9802
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/product/api/air.toml
    networks:
      - goms_net

  product-rpc:
    image: cosmtrek/air:latest
    container_name: goms_service_product_rpc
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7902:7902
      - 9902:9902
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/product/rpc/air.toml
    networks:
      - goms_net


  order-api:
    image: cosmtrek/air:latest
    container_name: goms_service_order_api
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7803:7803
      - 9803:9803
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/order/api/air.toml
    networks:
      - goms_net

  order-rpc:
    image: cosmtrek/air:latest
    container_name: goms_service_order_rpc
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7903:7903
      - 9903:9903
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/order/rpc/air.toml
    networks:
      - goms_net

  order-mq:
    image: cosmtrek/air:latest
    container_name: goms_service_order_mq
    environment:
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
      GOPATH: /gopath
    ports:
      - 7703:7703
    working_dir: /app
    volumes:
      - .:/app
      - /bind/data/air:/gopath
    privileged: true
    restart: always
    command: -c service/order/mq/air.toml
    networks:
      - goms_net

networks:
  goms_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

