// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "goms/service/order/api/internal/handler/order"
	"goms/service/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthConvertor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/submit",
					Handler: order.SubmitHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: order.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: order.DetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/order/v1"),
	)
}
