// Code generated by goctl. DO NOT EDIT.
package types

type AuthReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}
