Clusters:
- Input:
    Kafka:
      Name: gostash
      Brokers:
        - "goms_kafka:9092"
      Topics:
        - goms-log
      Group: gostash
      Consumers: 8
  Filters:
#    - Action: drop
#      Conditions:
#        - Key: k8s_container_name
#          Value: "-rpc"
#          Type: contains
#        - Key: level
#          Value: info
#          Type: match
#          Op: and
    - Action: remove_field
      Fields:
        - message
        - _source
        - _type
        - _score
        - _id
        - "@version"
        - topic
        - index
        - beat
        - docker_container
        - offset
        - prospector
        - source
        - stream
        - "@metadata"
    - Action: transfer
      Field: message
      Target: data
  Output:
    ElasticSearch:
      Hosts:
        - http://goms_elasticsearch:9200
      Index: "goms-{{yyyy-MM-dd}}"
