// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"goms/app/user/rpc/internal/logic"
	"goms/app/user/rpc/internal/svc"
	"goms/app/user/rpc/pb/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) AuthLogin(ctx context.Context, in *user.AuthReq) (*user.AuthResp, error) {
	l := logic.NewAuthLoginLogic(ctx, s.svcCtx)
	return l.AuthLogin(in)
}

func (s *UserServer) AuthRegister(ctx context.Context, in *user.AuthReq) (*user.AuthResp, error) {
	l := logic.NewAuthRegisterLogic(ctx, s.svcCtx)
	return l.AuthRegister(in)
}

func (s *UserServer) UserCurrent(ctx context.Context, in *user.UserCurrentReq) (*user.UserCurrentResp, error) {
	l := logic.NewUserCurrentLogic(ctx, s.svcCtx)
	return l.UserCurrent(in)
}
