# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  #Auth
  - job_name: 'auth-api'
    static_configs:
      - targets: [ 'goms_service_auth_api:7800' ]
        labels:
          job: auth-api
          app: auth-api
          env: dev

  #User
  - job_name: 'user-api'
    static_configs:
      - targets: [ 'goms_service_user_api:7801' ]
        labels:
          job: user-api
          app: user-api
          env: dev
          
  - job_name: 'user-rpc'
    static_configs:
      - targets: [ 'goms_service_user_rpc:7901' ]
        labels:
          job: user-rpc
          app: user-rpc
          env: dev
  
  #Product
  - job_name: 'product-api'
    static_configs:
      - targets: [ 'goms_service_product_api:7802' ]
        labels:
          job: product-api
          app: product-api
          env: dev
          
  - job_name: 'product-rpc'
    static_configs:
      - targets: [ 'goms_service_product_rpc:7902' ]
        labels:
          job: product-rpc
          app: product-rpc
          env: dev
        
  #Order
  - job_name: 'order-api'
    static_configs:
      - targets: [ 'goms_service_order_api:7803' ]
        labels:
          job: order-api
          app: order-api
          env: dev
          
  - job_name: 'order-rpc'
    static_configs:
      - targets: [ 'goms_service_order_rpc:7903' ]
        labels:
          job: order-rpc
          app: order-rpc
          env: dev

  - job_name: 'order-mq'
    static_configs:
      - targets: [ 'goms_service_order_mq:7703' ]
        labels:
          job: order-mq
          app: order-mq
          env: dev
