// Code generated by goctl. DO NOT EDIT.
package types

type ListItem struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Category int32  `json:"category"`
	Stock    int64  `json:"stock"`
	Price    int64  `json:"price"`
}

type ListReq struct {
	Search   string `json:"search"`
	Category int32  `json:"category" validate:"gte=0,lte=2"`
	Page     int32  `json:"page" validate:"gte=1"`
	PageSize int32  `json:"pageSize" validate:"gte=5,lte=100"`
}

type ListResp struct {
	List []ListItem `json:"list"`
	Page Page       `json:"page"`
}

type IdReq struct {
	ID int64 `json:"id" validate:"gte=1"`
}

type DetailResp struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Category    int32  `json:"category"`
	Stock       int64  `json:"stock"`
	Price       int64  `json:"price"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
}

type EditReq struct {
	ID          int64  `json:"id" validate:"gte=0"`
	Title       string `json:"title" validate:"required"`
	Category    int32  `json:"category" validate:"gte=1,lte=2"`
	Stock       int64  `json:"stock" validate:"gte=0"`
	Price       int64  `json:"price" validate:"gte=0"`
	Description string `json:"description"`
}

type IdResp struct {
	ID int64 `json:"id"`
}

type Page struct {
	Page     int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	Total    int64 `json:"total"`
}
