// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderclient

import (
	"context"

	"goms/service/order/rpc/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq   = order.CreateReq
	DetailReply = order.DetailReply
	Empty       = order.Empty
	IdReq       = order.IdReq
	ListItem    = order.ListItem
	ListReply   = order.ListReply
	ListReq     = order.ListReq
	Page        = order.Page
	Product     = order.Product
	UserIdReq   = order.UserIdReq

	Order interface {
		List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListReply, error)
		Detail(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*DetailReply, error)
		// DTM
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Empty, error)
		CreateRollback(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Empty, error)
		// Internal
		CheckPaymentTimeout(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListReply, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultOrder) Detail(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*DetailReply, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}

// DTM
func (m *defaultOrder) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultOrder) CreateRollback(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateRollback(ctx, in, opts...)
}

// Internal
func (m *defaultOrder) CheckPaymentTimeout(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CheckPaymentTimeout(ctx, in, opts...)
}
