// Code generated by goctl. DO NOT EDIT.
package types

type ListItem struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Category int32  `json:"category"`
	Stock    int64  `json:"stock"`
	Price    int64  `json:"price"`
}

type ListReq struct {
	Search   string `form:"search,optional"`
	Category int32  `form:"category,optional,range=[1:2]"`
	Page     int32  `form:"page,range=[1:]"`
	PageSize int32  `form:"pageSize,range=[5:100]"`
}

type ListResp struct {
	List []ListItem `json:"list"`
	Page Page       `json:"page"`
}

type IdReq struct {
	ID int64 `form:"id" validate:"gte=1"`
}

type DetailResp struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Category    int32  `json:"category"`
	Stock       int64  `json:"stock"`
	Price       int64  `json:"price"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
}

type EditReq struct {
	ID          int64  `json:"id,optional,range=[1:]"`
	Title       string `json:"title"`
	Category    int32  `json:"category,range=[1:2]"`
	Stock       int64  `json:"stock,optional,range=[1:]"`
	Price       int64  `json:"price,optional,range=[1:]"`
	Description string `json:"description,optional"`
}

type IdResp struct {
	ID int64 `json:"id"`
}

type Page struct {
	Page     int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	Total    int64 `json:"total"`
}
