filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*-json.log
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.kafka:
  hosts: ["goms_kafka:9092"]
  #kafka-topics.sh --create --topic goms-log --replication-factor 1 --partitions 1 --bootstrap-server localhost:9092
  topic: goms-log
  partition.hash:
    reachable_only: true
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000