// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "goms/service/auth/api/internal/handler/auth"
	token "goms/service/auth/api/internal/handler/token"
	"goms/service/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/verify",
				Handler: token.VerifyHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/auth/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/refresh",
				Handler: token.RefreshHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtRefresh.AccessSecret),
		rest.WithPrefix("/auth/v1"),
	)
}
