// Code generated by goctl. DO NOT EDIT.
package types

type AuthReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type AuthResp struct {
	Token string `json:"token"`
}

type CurrentResp struct {
	Username string `json:"username"`
}
