// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"goms/app/order/rpc/internal/logic"
	"goms/app/order/rpc/internal/svc"
	"goms/app/order/rpc/pb/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Submit(ctx context.Context, in *order.SubmitReq) (*order.Empty, error) {
	l := logic.NewSubmitLogic(ctx, s.svcCtx)
	return l.Submit(in)
}

func (s *OrderServer) List(ctx context.Context, in *order.ListReq) (*order.ListReply, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *OrderServer) Detail(ctx context.Context, in *order.IdReq) (*order.DetailReply, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
