// Code generated by goctl. DO NOT EDIT.
package types

type ProductsReq struct {
	ID     int64 `json:"id" validate:"gte=1"`
	Amount int64 `json:"amount" validate:"gte=1"`
}

type ProductsResp struct {
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	Price  int64  `json:"price"`
	Amount int64  `json:"amount"`
}

type SubmitReq struct {
	Products  []ProductsReq `json:"products"`
	Consignee string        `json:"consignee"`
	Phone     string        `json:"phone"`
	Address   string        `json:"address"`
}

type ListReq struct {
	Status   int32 `form:"status,optional" validate:"gte=0,lte=4"`
	Page     int32 `form:"page" validate:"gte=1"`
	PageSize int32 `form:"pageSize" validate:"gte=5,lte=100"`
}

type ListItem struct {
	ID          int64          `json:"id"`
	Status      int32          `json:"status"`
	Products    []ProductsResp `json:"products"`
	TotalAmount int64          `json:"totalAmount"`
	TotalPrice  int64          `json:"totalPrice"`
}

type ListResp struct {
	List []ListItem `json:"list"`
	Page Page       `json:"page"`
}

type IdReq struct {
	ID int64 `form:"id" validate:"gte=1"`
}

type DetailResp struct {
	ID          int64          `json:"id"`
	Status      int32          `json:"status"`
	Products    []ProductsResp `json:"products"`
	Consignee   string         `json:"consignee"`
	Phone       string         `json:"phone"`
	Address     string         `json:"address"`
	TotalAmount int64          `json:"totalAmount"`
	TotalPrice  int64          `json:"totalPrice"`
	CreatedAt   int64          `json:"createdAt"`
}

type PaymentReq struct {
	ID       int64  `json:"id" validate:"gte=1"`
	Platform string `json:"platform"`
}

type PaymentResp struct {
	TotalPrice int64  `json:"totalPrice"`
	PaySign    string `json:"paySign"`
}

type Page struct {
	Page     int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	Total    int64 `json:"total"`
}
